version: '3.4'

services:
  app:
    image: odadosufal/odadosufal-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgdc-api
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: production
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres
  redis:
    image: redis:5.0.7
    container_name: redis
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidekiq
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: production
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
