form_expiration:
  cron: "0 0 * * *"
  class: "Schedules::FormExpirationWorker"
form_init:
  cron: "0 0 * * *"
  class: "Schedules::FormInitWorker"
form_ending:
  cron: "30 0 * * *"
  class: "Schedules::NotifyUsersFormExpirationWorker"
