form_expiration:
  cron: "0 7 * * *"
  class: "Schedules::FormExpirationWorker"
form_init:
  cron: "0 7 * * *"
  class: "Schedules::FormInitWorker"
form_ending:
  cron: "30 19 * * *"
  class: "Schedules::NotifyUsersFormExpirationWorker"
