form_expiration:
  cron: "0 0 * * *"
  class: "Schedules::FormExpirationWorker"
form_init:
  cron: "0 0 * * *"
  class: "Schedules::FormInitWorker"
form_ending:
  cron: "40 18 * * *"
  class: "Schedules::NotifyUsersFormExpirationWorker"
