name: Deploy to Production
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Create env file
        run: touch .env

      - name: Copy env file from secrets
        run: echo "${{ secrets.SERVER_ENV_PROD }}" > .env

      - name: Build docker-compose
        run: docker-compose up --build -d
