name: Deploy to Production
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Deploy Ruby on Rails app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir pgdc-api
            cd pgdc-api
            git clone git@github.com:PDS-UFAL/pgdc-api.git
            touch .env
            echo "${{ secrets.SERVER_ENV_PROD }}" > .env
            cat .env
            docker-compose up --build -d
